# Generated by Django 4.2.24 on 2025-09-17 13:15

import django.core.validators
from django.db import migrations, models
import tasks.models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.CharField(max_length=64, unique=True, validators=[tasks.models.validate_tag_name]),
        ),
        migrations.AlterField(
            model_name='task',
            name='estimate',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), tasks.models.validate_task_estimate]),
        ),
        migrations.AlterField(
            model_name='task',
            name='title',
            field=models.CharField(max_length=200, validators=[tasks.models.validate_task_title]),
        ),
    ]
