# Generated by Django 4.2.24 on 2025-09-17 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_alter_tag_name_alter_task_estimate_alter_task_title'),
    ]

    operations = [
        # Add indexes for similarity query optimization
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['title'], name='tasks_task_title_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['description'], name='tasks_task_description_idx'),
        ),
        # Add composite index for activity queries (task_id + created_at already exists)
        # Add index for tags many-to-many relationship optimization
        migrations.RunSQL(
            "CREATE INDEX IF NOT EXISTS tasks_task_tags_tag_id_idx ON tasks_task_tags (tag_id);",
            reverse_sql="DROP INDEX IF EXISTS tasks_task_tags_tag_id_idx;"
        ),
        migrations.RunSQL(
            "CREATE INDEX IF NOT EXISTS tasks_task_tags_task_id_idx ON tasks_task_tags (task_id);",
            reverse_sql="DROP INDEX IF EXISTS tasks_task_tags_task_id_idx;"
        ),
    ]
