# Generated by Django 4.2.24 on 2025-09-18 00:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0005_alter_task_options_alter_taskactivity_options_and_more'),
    ]

    operations = [
    ]
