# Generated by Django 4.2.24 on 2025-09-18 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0006_auto_20250918_0025'),
    ]

    operations = [
        # Remove the many-to-many field
        migrations.RemoveField(
            model_name='task',
            name='tags',
        ),
        
        # Add the new JSONField
        migrations.AddField(
            model_name='task',
            name='tags',
            field=models.JSONField(
                default=list,
                blank=True,
                help_text="Array of tag names as strings"
            ),
        ),
    ]
